In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_clinical_patient=pd.read_csv("data_clinical_patient.txt",sep="\t")

In [ ]:
df_clinical_patient

,#Patient Identifier,Sex,Patient's Vital Status,Smoking History,Overall Survival (Months),Overall Survival Status
0,#Patient identifier,Sex,The survival state of the person.,Indicates if person has a history of smoking.,Overall survival in months since initial diago...,Overall patient survival status.
1,#STRING,STRING,STRING,STRING,NUMBER,STRING
2,#1,1,1,1,1,1
3,PATIENT_ID,SEX,VITAL_STATUS,SMOKING_HISTORY,OS_MONTHS,OS_STATUS
4,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING
...,...,...,...,...,...,...
10335,P-0012442,Female,ALIVE,Unknown,4.7,0:LIVING
10336,P-0012500,Female,ALIVE,Prev/Curr Smoker,4.8,0:LIVING
10337,P-0012524,Male,DECEASED,Never,5.33,1:DECEASED
10338,P-0012557,Female,ALIVE,Prev/Curr Smoker,NaN,0:LIVING
10339,P-0012622,Male,ALIVE,Never,13.81,0:LIVING

In [ ]:
df_clinical_sample=pd.read_csv("data_clinical_sample.txt",sep="\t",comment='#', skiprows=1)

In [ ]:
df_clinical_sample

,PATIENT_ID,SAMPLE_ID,SAMPLE_COLLECTION_SOURCE,SPECIMEN_PRESERVATION_TYPE,SPECIMEN_TYPE,DNA_INPUT,SAMPLE_COVERAGE,TUMOR_PURITY,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TMB_NONSYNONYMOUS
0,P-0000004,P-0000004-T01-IM3,Outside,FFPE,Biopsy,250.0,428.0,50.0,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
1,P-0000015,P-0000015-T01-IM3,In-House,FFPE,Biopsy,198.0,281.0,40.0,Matched,Metastasis,Breast,Liver,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,7.764087
2,P-0000023,P-0000023-T01-IM3,In-House,FFPE,Biopsy,250.0,454.0,30.0,Matched,Primary,Peritoneum,Not Applicable,Tumor,PEMESO,Mesothelioma,Peritoneal Mesothelioma,Matched,5.545777
3,P-0000024,P-0000024-T01-IM3,In-House,FFPE,Resection,250.0,1016.0,40.0,Matched,Metastasis,Uterus,Lung,Tumor,UEC,Endometrial Cancer,Uterine Endometrioid Carcinoma,Matched,6.654932
4,P-0000025,P-0000025-T02-IM5,In-House,FFPE,Biopsy,250.0,1147.0,30.0,Matched,Metastasis,Uterus,Peritoneum,Tumor,USC,Endometrial Cancer,Uterine Serous Carcinoma/Uterine Papillary Ser...,Matched,1.957439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10940,P-0012442,P-0012442-T01-IM5,In-House,FFPE,Resection,250.0,815.0,30.0,Matched,Primary,Pancreas,Not Applicable,Tumor,PAAD,Pancreatic Cancer,Pancreatic Adenocarcinoma,Matched,1.957439
10941,P-0012500,P-0012500-T01-IM5,In-House,FFPE,Resection,250.0,812.0,50.0,Matched,Primary,Breast,Not Applicable,Tumor,BRCA,Breast Cancer,Invasive Breast Carcinoma,Matched,1.957439
10942,P-0012524,P-0012524-T01-IM5,In-House,FFPE,Biopsy,250.0,995.0,70.0,Unmatched,Primary,Lymph node,Not Applicable,Tumor,DLBCLNOS,Mature B-Cell Neoplasms,"Diffuse Large B-Cell Lymphoma, NOS",Unmatched,10.765917
10943,P-0012557,P-0012557-T01-IM5,Outside,FFPE,Biopsy,90.0,297.0,40.0,Matched,Metastasis,Bladder,Soft Tissue,Tumor,BLCA,Bladder Cancer,Bladder Urothelial Carcinoma,Matched,14.680795
10944,P-0012622,P-0012622-T01-IM5,Outside,FFPE,Resection,250.0,843.0,80.0,Matched,Primary,Mesentery,Not Applicable,Tumor,SARCNOS,Soft Tissue Sarcoma,"Sarcoma, NOS",Matched,3.914879

In [ ]:
print(df_clinical_sample.columns)
#Matched status/somatic_status/sample_type
# Matched: somatic mutations only in cancer cells
#Unmatched:  may be Germline mutations
# dropp unmatched

Index(['PATIENT_ID', 'SAMPLE_ID', 'SAMPLE_COLLECTION_SOURCE',
       'SPECIMEN_PRESERVATION_TYPE', 'SPECIMEN_TYPE', 'DNA_INPUT',
       'SAMPLE_COVERAGE', 'TUMOR_PURITY', 'MATCHED_STATUS', 'SAMPLE_TYPE',
       'PRIMARY_SITE', 'METASTATIC_SITE', 'SAMPLE_CLASS', 'ONCOTREE_CODE',
       'CANCER_TYPE', 'CANCER_TYPE_DETAILED', 'SOMATIC_STATUS',
       'TMB_NONSYNONYMOUS'],
      dtype='object')

In [ ]:
df_clinical_sample['SAMPLE_TYPE'].value_counts()

Primary       6213
Metastasis    4731
Name: SAMPLE_TYPE, dtype: int64

In [ ]:
df_clinical_sample.groupby('PATIENT_ID').count()

,SAMPLE_ID,SAMPLE_COLLECTION_SOURCE,SPECIMEN_PRESERVATION_TYPE,SPECIMEN_TYPE,DNA_INPUT,SAMPLE_COVERAGE,TUMOR_PURITY,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TMB_NONSYNONYMOUS
PATIENT_ID,,,,,,,,,,,,,,,,,
P-0000004,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0000015,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0000023,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0000024,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0000025,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P-0012442,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0012500,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0012524,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0012557,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P-0012622,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
df_clinical_sample.groupby('PATIENT_ID').count()['SAMPLE_ID'].value_counts()

1    9774
2     519
3      40
4       2
5       1
Name: SAMPLE_ID, dtype: int64

In [ ]:
df_clinical_sample['PATIENT_ID'].value_counts()

P-0000377    5
P-0001104    4
P-0004910    4
P-0004430    3
P-0002273    3
            ..
P-0004072    1
P-0004073    1
P-0004074    1
P-0004075    1
P-0012622    1
Name: PATIENT_ID, Length: 10336, dtype: int64

In [ ]:
df_clinical_sample[df_clinical_sample['PATIENT_ID']=='P-0000377']

,PATIENT_ID,SAMPLE_ID,SAMPLE_COLLECTION_SOURCE,SPECIMEN_PRESERVATION_TYPE,SPECIMEN_TYPE,DNA_INPUT,SAMPLE_COVERAGE,TUMOR_PURITY,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TMB_NONSYNONYMOUS
318,P-0000377,P-0000377-T01-IM3,In-House,FFPE,Biopsy,117.7,706.0,70.0,Matched,Metastasis,Prostate,Bone,Tumor,PRAD,Prostate Cancer,Prostate Adenocarcinoma,Matched,6.654932
319,P-0000377,P-0000377-T03-IM3,In-House,FFPE,Biopsy,250.0,805.0,80.0,Matched,Primary,Prostate,Not Applicable,Tumor,PRAD,Prostate Cancer,Prostate Adenocarcinoma,Matched,9.982398
320,P-0000377,P-0000377-T04-IM5,In-House,DNA,Biopsy,250.0,834.0,30.0,Matched,Metastasis,Prostate,Liver,Tumor,PRAD,Prostate Cancer,Prostate Adenocarcinoma,Matched,5.872318
321,P-0000377,P-0000377-T05-IM5,In-House,FFPE,Biopsy,250.0,1049.0,30.0,Matched,Metastasis,Prostate,Liver,Tumor,PRAD,Prostate Cancer,Prostate Adenocarcinoma,Matched,0.978720
322,P-0000377,P-0000377-T02-IM3,Outside,FFPE,Resection,250.0,564.0,60.0,Matched,Metastasis,Prostate,Bone,Tumor,PRAD,Prostate Cancer,Prostate Adenocarcinoma,Matched,3.327466

In [ ]:
df_data_mut=pd.read_csv("data_mutation_clean.csv")

In [ ]:
df_data_mut['Tumor_Sample_Barcode']

0        P-0000004
1        P-0000004
2        P-0000004
3        P-0000004
4        P-0000004
           ...
78258    P-0012524
78259    P-0012524
78260    P-0012524
78261    P-0012524
78262    P-0005919
Name: Tumor_Sample_Barcode, Length: 78263, dtype: object

In [ ]:
## Join two data frames
merged_inner = pd.merge(left=df_clinical_patient, right=df_data_mut, left_on='#Patient Identifier', right_on='Tumor_Sample_Barcode')

In [ ]:
merged_inner

,#Patient Identifier,Sex,Patient's Vital Status,Smoking History,Overall Survival (Months),Overall Survival Status,Unnamed: 0,Hugo_Symbol,Entrez_Gene_Id,Center,...,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,cDNA_change,protein1Tumor_Sample_Barcode_new,protein1Tumor_Sample_Barcode_new_1
0,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,0,SPEN,NaN,NaN,...,p.Ile3661Phe,p.I3661F,ENST00000375759,NM_015001.2,3661.0,Att/Ttt,0,c.10981A>T,P-0000004,P-0000004
1,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,1,ALK,NaN,NaN,...,p.Val476Ala,p.V476A,ENST00000389048,NM_004304.4,476.0,gTg/gCg,0,c.1427T>C,P-0000004,P-0000004
2,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,2,PDCD1,NaN,NaN,...,p.Ala215Val,p.A215V,ENST00000334409,NM_005018.2,215.0,gCc/gTc,0,c.644C>T,P-0000004,P-0000004
3,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,3,MAP3K1,NaN,NaN,...,p.Ser939Cys,p.S939C,ENST00000399503,NM_005921.1,939.0,tCt/tGt,0,c.2816C>G,P-0000004,P-0000004
4,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,4,FLT4,NaN,NaN,...,p.Arg1324Leu,p.R1324L,ENST00000261937,NM_182925.4,1324.0,cGg/cTg,0,c.3971G>T,P-0000004,P-0000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78240,P-0012557,Female,ALIVE,Prev/Curr Smoker,NaN,0:LIVING,75892,IRF4,NaN,NaN,...,p.Ser309ArgfsTer72,p.S309Rfs*72,ENST00000380956,NM_001195286.1,308.0,ctGAGCCACCTG/ct,0,c.927_936delCCACCTGGAG,P-0012557-T01-IM5,P-0012557-T01-IM5
78241,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75893,TERT,NaN,NaN,...,p.Cys842Phe,p.C842F,ENST00000310581,NM_198253.2,842.0,tGc/tTc,0,c.2525G>T,P-0012622-T01-IM5,P-0012622-T01-IM5
78242,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75894,PTPRD,NaN,NaN,...,p.Ala41Val,p.A41V,ENST00000356435,NaN,41.0,gCc/gTc,0,c.122C>T,P-0012622-T01-IM5,P-0012622-T01-IM5
78243,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75895,ERCC2,NaN,NaN,...,p.Gln279Leu,p.Q279L,ENST00000391945,NM_000400.3,279.0,cAg/cTg,0,c.836A>T,P-0012622-T01-IM5,P-0012622-T01-IM5
78244,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75896,ATRX,NaN,NaN,...,p.Lys1896Ter,p.K1896*,ENST00000373344,NM_000489.3,1896.0,Aaa/Taa,0,c.5686A>T,P-0012622-T01-IM5,P-0012622-T01-IM5

In [ ]:
## Join two data frames
merged_inner_final = pd.merge(left=merged_inner, right=df_clinical_sample, left_on='#Patient Identifier', right_on='PATIENT_ID')

In [ ]:
merged_inner_final

,#Patient Identifier,Sex,Patient's Vital Status,Smoking History,Overall Survival (Months),Overall Survival Status,Unnamed: 0,Hugo_Symbol,Entrez_Gene_Id,Center,...,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TMB_NONSYNONYMOUS
0,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,0,SPEN,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
1,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,1,ALK,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
2,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,2,PDCD1,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
3,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,3,MAP3K1,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
4,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,4,FLT4,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86787,P-0012557,Female,ALIVE,Prev/Curr Smoker,NaN,0:LIVING,75892,IRF4,NaN,NaN,...,Matched,Metastasis,Bladder,Soft Tissue,Tumor,BLCA,Bladder Cancer,Bladder Urothelial Carcinoma,Matched,14.680795
86788,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75893,TERT,NaN,NaN,...,Matched,Primary,Mesentery,Not Applicable,Tumor,SARCNOS,Soft Tissue Sarcoma,"Sarcoma, NOS",Matched,3.914879
86789,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75894,PTPRD,NaN,NaN,...,Matched,Primary,Mesentery,Not Applicable,Tumor,SARCNOS,Soft Tissue Sarcoma,"Sarcoma, NOS",Matched,3.914879
86790,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75895,ERCC2,NaN,NaN,...,Matched,Primary,Mesentery,Not Applicable,Tumor,SARCNOS,Soft Tissue Sarcoma,"Sarcoma, NOS",Matched,3.914879
86791,P-0012622,Male,ALIVE,Never,13.81,0:LIVING,75896,ATRX,NaN,NaN,...,Matched,Primary,Mesentery,Not Applicable,Tumor,SARCNOS,Soft Tissue Sarcoma,"Sarcoma, NOS",Matched,3.914879

In [ ]:

df_data_mut_cancer=merged_inner_final[merged_inner_final['CANCER_TYPE']=='Breast Cancer']

In [ ]:
df_data_mut_cancer

,#Patient Identifier,Sex,Patient's Vital Status,Smoking History,Overall Survival (Months),Overall Survival Status,Unnamed: 0,Hugo_Symbol,Entrez_Gene_Id,Center,...,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TMB_NONSYNONYMOUS
0,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,0,SPEN,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
1,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,1,ALK,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
2,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,2,PDCD1,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
3,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,3,MAP3K1,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
4,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,4,FLT4,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86226,P-0012396,Female,ALIVE,Prev/Curr Smoker,4.47,0:LIVING,75851,LATS2,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,7.829758
86227,P-0012396,Female,ALIVE,Prev/Curr Smoker,4.47,0:LIVING,75852,MAP2K4,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,7.829758
86228,P-0012396,Female,ALIVE,Prev/Curr Smoker,4.47,0:LIVING,75853,PTPRS,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,7.829758
86760,P-0012500,Female,ALIVE,Prev/Curr Smoker,4.8,0:LIVING,75876,PIK3CA,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,BRCA,Breast Cancer,Invasive Breast Carcinoma,Matched,1.957439
86761,P-0012500,Female,ALIVE,Prev/Curr Smoker,4.8,0:LIVING,75877,CBFB,NaN,NaN,...,Matched,Primary,Breast,Not Applicable,Tumor,BRCA,Breast Cancer,Invasive Breast Carcinoma,Matched,1.957439

In [ ]:
#df_data_mut_patient=df_data_mut_final.groupby(['Tumor_Sample_Barcode','Hugo_Symbol'])
df_data_mut_cancer = df_data_mut_cancer.groupby('Tumor_Sample_Barcode').apply(lambda x: x['Hugo_Symbol'].unique())

In [ ]:
df_data_mut_cancer

Tumor_Sample_Barcode
P-0000004    [SPEN, ALK, PDCD1, MAP3K1, FLT4, NOTCH4, MLL3,...
P-0000015        [ALK, PIK3CA, ESR1, CDK4, TP53, RNF43, GATA3]
P-0000041                                  [PIK3CA, TP53, NF2]
P-0000057               [PIK3CA, BARD1, MAP3K13, NOTCH4, TP53]
P-0000058                                               [TP53]
                                   ...
P-0012318                                      [PIK3CA, GATA3]
P-0012362                             [BCOR, FLT1, CDH1, TBX3]
P-0012372                               [PIK3CA, ARID1B, PTEN]
P-0012396    [PTEN, PIK3CA, GRIN2A, ATM, LATS2, MAP2K4, PTPRS]
P-0012500                                       [PIK3CA, CBFB]
Length: 1203, dtype: object

In [ ]:
genes_mutated=df_data_mut_cancer.to_list()

In [ ]:
genes_mutated

[array(['SPEN', 'ALK', 'PDCD1', 'MAP3K1', 'FLT4', 'NOTCH4', 'MLL3', 'MLL2',
        'TSHR', 'AKT1', 'TSC2', 'RNF43', 'NOTCH3', 'TP53'], dtype=object),
 array(['ALK', 'PIK3CA', 'ESR1', 'CDK4', 'TP53', 'RNF43', 'GATA3'],
       dtype=object),
 array(['PIK3CA', 'TP53', 'NF2'], dtype=object),
 array(['PIK3CA', 'BARD1', 'MAP3K13', 'NOTCH4', 'TP53'], dtype=object),
 array(['TP53'], dtype=object),
 array(['ESR1', 'CD276', 'TP53', 'RARA', 'MLL3', 'BRD4'], dtype=object),
 array(['PIK3CA', 'SF3B1', 'HRAS', 'CBL', 'POLE', 'RB1', 'JAK3', 'ERG',
        'TP53'], dtype=object),
 array(['MSH6', 'ASXL1'], dtype=object),
 array(['PIK3CA', 'PRDM1', 'ARID2', 'MAP2K2', 'MAP3K1'], dtype=object),
 array(['TP53', 'PTEN'], dtype=object),
 array(['TNFAIP3'], dtype=object),
 array(['FAT1', 'TP53', 'MAPK1', 'PTEN'], dtype=object),
 array(['PTEN', 'FOXA1', 'CDH1', 'MLL'], dtype=object),
 array(['FAT1', 'POLE', 'FLCN', 'TP53'], dtype=object),
 array(['PIK3CA', 'NF1'], dtype=object),
 array(['ARID1A', 'ASXL2', 'FLT4', 'CDK12', 'SMAD4', 'TMPRSS2'],
       dtype=object),
 array(['AXIN1', 'NCOR1', 'SMARCA4', 'ASXL1'], dtype=object),
 array(['SF3B1', 'PIK3CA', 'PTEN', 'TP53', 'MLL3'], dtype=object),
 array(['PTEN'], dtype=object),
 array(['PTEN', 'TP53'], dtype=object),
 array(['PIK3CA', 'SPEN', 'GATA3'], dtype=object),
 array(['PIK3CA', 'TET2', 'FGFR4', 'ROS1', 'MLL3', 'SOX17', 'GATA3',
        'SMARCD1', 'PTPN11', 'DICER1', 'NTRK3', 'PIK3R2', 'MED12', 'MTOR',
        'JAK1', 'NOTCH2', 'MSH2', 'REL', 'ATR', 'FAT1', 'IL7R', 'EZH2',
        'PTPRD', 'FANCC', 'TET1', 'ERBB3', 'POLE', 'FLT3', 'DIS3', 'ERCC4',
        'NF1', 'BRCA1', 'DOT1L', 'AXL', 'KDM6A', 'TBX3'], dtype=object),
 array(['MAP2K4', 'ESR1', 'PAX5', 'GLI1', 'SOX9', 'SMARCA4'], dtype=object),
 array(['MED12'], dtype=object),
 array(['PIK3CA', 'MAP3K1', 'MLL', 'CDH1'], dtype=object),
 array(['PRDM1', 'MLL2'], dtype=object),
 array(['PAK7', 'GATA3'], dtype=object),
 array(['PIK3CA', 'NF1', 'CDH1', 'SPEN', 'MCL1', 'ALK', 'NFE2L2', 'SETD2',
        'FOXP1', 'PIK3CB', 'FLT4', 'SMO', 'ATM', 'MLL2', 'FLT1', 'BRCA2',
        'IRS2', 'PDPK1', 'PALB2', 'SOX9', 'SMAD4', 'BCOR'], dtype=object),
 array(['MLL3', 'PIK3CA'], dtype=object),
 array(['PIK3CA', 'SF3B1', 'MAP3K1', 'PTEN'], dtype=object),
 array(['NOTCH2', 'PMS1', 'PIK3CA', 'MAP2K1', 'PALB2', 'TP53'],
       dtype=object),
 array(['TP53', 'PTEN', 'RB1', 'BAP1', 'MRE11A'], dtype=object),
 array(['HGF', 'KDM5A', 'IGF1', 'TP53'], dtype=object),
 array(['TP53'], dtype=object),
 array(['AKT1', 'TP53', 'MAP3K1', 'BRCA2', 'CDK12', 'RUNX1'], dtype=object),
 array(['PARP1', 'MSH2', 'RASA1', 'ESR1', 'MLL3', 'ERBB3', 'TBX3', 'CDH1',
        'PTEN'], dtype=object),
 array(['PIK3CA', 'JAK1', 'MLL2', 'DICER1', 'PAK7', 'ERBB2', 'CDKN2A'],
       dtype=object),
 array(['PIK3CA', 'CDH1'], dtype=object),
 array(['PTEN', 'CTCF', 'NF1', 'PIK3R1', 'TP53'], dtype=object),
 array(['TP53', 'RB1'], dtype=object),
 array(['PIK3CA', 'BAP1', 'ERCC2', 'CHEK2'], dtype=object),
 array(['PIK3CA', 'MPL', 'FAT1', 'PLK2', 'FGFR2', 'BRCA2', 'SMAD4',
        'BRIP1'], dtype=object),
 array(['PIK3CA', 'EPHB1', 'TSC2', 'PIK3C3', 'SMARCB1', 'MAP3K1', 'CDH1'],
       dtype=object),
 array(['RICTOR', 'ESR1', 'ATM'], dtype=object),
 array(['PIK3CA', 'TP53', 'MPL', 'PPM1D', 'ZRSR2', 'APC'], dtype=object),
 array(['DDR2', 'TP53', 'RUNX1', 'MLL3'], dtype=object),
 array(['TP53', 'NF1'], dtype=object),
 array(['MSH6', 'SOX17', 'AXIN2', 'PIK3CB', 'MTOR', 'RAD54L', 'NOTCH2',
        'HIST3H3', 'ERBB4', 'SHQ1', 'PIK3CA', 'FLT4', 'NOTCH4', 'VEGFA',
        'LATS1', 'HGF', 'MET', 'JAK2', 'TBX3', 'AXIN1', 'DOT1L', 'CCNE1',
        'ARID1A', 'RASA1', 'IKZF1', 'FOXO1', 'MGA', 'PLCG2'], dtype=object),
 array(['PIK3CA', 'RASA1', 'FOXA1'], dtype=object),
 array(['ARID1A', 'CARD11', 'ARID5B', 'TP53', 'CDKN2A'], dtype=object),
 array(['PIK3CA', 'ERCC4', 'ESR1', 'TP53'], dtype=object),
 array(['PBRM1', 'MLL', 'BRCA2', 'TP53', 'ATM'], dtype=object),
 array(['PIK3CA', 'ATR', 'CDH1', 'FOXA1', 'RUNX1'], dtype=object),
 array(['PIK3CA'], dtype=object),
 array(['ERBB2'], dtype=object),
 array(['PIK3CA', 'ESR1', 'ARID1A', 'JAK1', 'GATA3', 'CIC', 'MAP3K1'],
       dtype=object),
 array(['PIK3CA', 'DNMT3A', 'MAX', 'CDH1'], dtype=object),
 array(['PIK3CA', 'DNMT3A', 'CTLA4', 'GATA2', 'FLT4', 'HIST1H1C', 'ROS1',
        'TBX3', 'IDH2', 'TP53'], dtype=object),
 array(['TP53', 'RAD50', 'IDH2'], dtype=object),
 array(['AKT1', 'CD276', 'CIC'], dtype=object),
 array(['TP53', 'IKZF1'], dtype=object),
 array(['PARP1', 'SOX17', 'GATA3', 'MCL1', 'NSD1'], dtype=object),
 array(['TP53'], dtype=object),
 array(['PARP1', 'PIK3R1', 'FANCA', 'JAK1', 'TP53', 'EP300'], dtype=object),
 array(['ERBB3', 'ARID2', 'PTPRT', 'PIK3CG'], dtype=object),
 array(['RAF1', 'PIK3CB', 'TP53'], dtype=object),
 array(['PIK3CA', 'SPOP', 'MAP2K4'], dtype=object),
 array(['RET', 'CDH1'], dtype=object),
 array(['PIK3CA', 'TP53', 'EPHA3', 'MLL3', 'RB1', 'ERCC5', 'AKT2',
        'PPP2R1A', 'PTPRT'], dtype=object),
 array(['FAT1', 'TP53', 'STAG2'], dtype=object),
 array(['TP53', 'PIK3CA', 'PIK3CB', 'RASA1', 'MDC1', 'SOX17', 'PTPRD',
        'POLE', 'IRS2', 'NF1', 'SMAD2', 'MED12', 'CDH1'], dtype=object),
 array(['TP53', 'MAP3K13'], dtype=object),
 array(['TP53', 'MLL2', 'SMAD3', 'CIC', 'STAG2', 'CDK8'], dtype=object),
 array(['NSD1', 'IRF4', 'MEN1', 'NKX2-1', 'TP53', 'BRCA1'], dtype=object),
 array(['ETV1', 'ATM', 'PIK3R1'], dtype=object),
 array(['TP53'], dtype=object),
 array(['PIK3CA', 'ESR1'], dtype=object),
 array(['PIK3CA', 'HIST1H3B', 'DAXX', 'PTEN', 'RNF43', 'CDH1', 'ESR1'],
       dtype=object),
 array(['PIK3CA', 'TERT', 'TP53', 'MSH6', 'TET2', 'ROS1', 'MLL3', 'KLF4',
        'TET1', 'ATM', 'DICER1', 'CREBBP', 'CDH1', 'NF1'], dtype=object),
 array(['PTEN'], dtype=object),
 array(['RUNX1'], dtype=object),
 array(['ESR1', 'GATA3', 'EGFR'], dtype=object),
 array(['EPCAM', 'FGFR2', 'BRCA2'], dtype=object),
 array(['PIK3CA', 'TP53', 'FOXA1', 'NF1', 'MAP3K1'], dtype=object),
 array(['PIK3CA', 'RAD54L'], dtype=object),
 array(['HIST1H3B', 'BRCA1', 'TP53'], dtype=object),
 array(['MAP3K13', 'PTEN', 'MEN1'], dtype=object),
 array(['TP53', 'JUN'], dtype=object),
 array(['CDH1', 'FOXA1', 'MAP2K4', 'RUNX1'], dtype=object),
 array(['ESR1', 'ARID1A', 'NOTCH4', 'TET1', 'DNMT3B'], dtype=object),
 array(['PIK3CA', 'MAP3K1', 'ROS1', 'PARK2', 'TP53', 'AURKA', 'PALB2',
        'ARID1B'], dtype=object),
 array(['PIK3CA', 'TP53', 'TET1', 'RB1'], dtype=object),
 array(['ESR1'], dtype=object),
 array(['SOX17', 'TP53'], dtype=object),
 array(['PTEN', 'TP53', 'TMPRSS2', 'STAG2'], dtype=object),
 array(['TP53'], dtype=object),
 array(['ARID1B', 'TET1', 'CDKN1B'], dtype=object),
 array(['PTPRS', 'MAP3K1', 'GATA3'], dtype=object),
 array(['PIK3CA', 'FOXL2', 'RICTOR', 'IKZF1', 'NOTCH1', 'BRCA1', 'PTPRS',
        'AXL', 'U2AF1', 'TP53'], dtype=object),
 array(['SMARCD1'], dtype=object),
 array(['PIK3CA', 'SF3B1', 'CDH1'], dtype=object),
 array(['ARID1A', 'FAM46C', 'MSH6', 'PTPRD', 'ERBB3', 'CDH1', 'TP53',
        'RPTOR', 'TOP1', 'PPP2R1A', 'FGFR4'], dtype=object),
 array(['ARID1A', 'EPHA5', 'MYOD1'], dtype=object),
 array(['GATA3', 'ATM'], dtype=object),
 array(['AKT1', 'TP53', 'RUNX1', 'FANCC', 'POLE', 'STK11', 'EP300',
        'FOXP1', 'SHQ1', 'RB1'], dtype=object),
 array(['PIK3CA'], dtype=object),
 array(['TP53', 'AKT3', 'ASXL2', 'MDM4', 'IRS1', 'FYN', 'DOT1L', 'DNMT3B',
        'IGF1R'], dtype=object),
 array(['TP53', 'KLF4', 'PTEN', 'BRCA2', 'AKT1', 'BARD1'], dtype=object),
 array(['PIK3CA', 'ERBB2', 'ALK', 'RICTOR', 'FOXA1', 'CDH1'], dtype=object),
 array(['DNMT3A', 'MSH6', 'TGFBR2', 'BAP1', 'KLF4', 'NOTCH1', 'SUZ12',
        'NOTCH3', 'GATA3', 'BRCA2', 'SMAD4'], dtype=object),
 array(['KDR', 'MLL'], dtype=object),
 array(['PIK3CA', 'IKBKE', 'MAP2K4', 'CDH1'], dtype=object),
 array(['GATA3'], dtype=object),
 array(['TNFAIP3', 'MLL3', 'PTPRD', 'GATA3', 'ARID2', 'BRCA2'],
       dtype=object),
 array(['PIK3CA', 'SF3B1', 'MLL3', 'FGFR1', 'TP53', 'PTPRS', 'CIC'],
       dtype=object),
 array(['PIK3CA', 'SPEN', 'IRS1', 'PBRM1', 'PIK3CG', 'LMO1', 'FLT1',
        'ERBB2', 'CDH1', 'ESR1'], dtype=object),
 array(['ESR1', 'RARA', 'CDH1', 'NCOR1'], dtype=object),
 array(['PIK3CA', 'STK11', 'TP53', 'MLL3', 'PTCH1', 'GATA3', 'MLL2',
        'CDH1', 'MAP2K2', 'EP300'], dtype=object),
 array(['GATA3', 'IKZF1', 'CREBBP', 'ATRX', 'CDH1'], dtype=object),
 array(['NOTCH1', 'BLM', 'PPP2R1A'], dtype=object),
 array(['GATA3', 'PIK3CA', 'NOTCH1', 'MAX', 'ARID1A'], dtype=object),
 array(['ERBB3', 'TP53', 'EP300'], dtype=object),
 array(['PIK3CA', 'MLL3', 'TP53', 'NCOR1'], dtype=object),
 array(['PIK3CA', 'TP53', 'AKT1', 'NOTCH2'], dtype=object),
 array(['FOXP1', 'MDC1', 'TP53'], dtype=object),
 array(['PIK3CA', 'TP53', 'EPHA3'], dtype=object),
 array(['PIK3CA', 'BARD1', 'ATM'], dtype=object),
 array(['PIK3CA', 'PMS1', 'MDC1', 'ROS1', 'FGFR1', 'PTEN', 'MLL2', 'TP53',
        'PTPRT'], dtype=object),
 array(['TP53', 'IFNGR1'], dtype=object),
 array(['MAP2K4'], dtype=object),
 array(['PIK3CA', 'ARID1A', 'TERT', 'ATM', 'FOXA1', 'RUNX1'], dtype=object),
 array(['RASA1', 'ARID2', 'BBC3', 'MAPK1'], dtype=object),
 array(['TP53'], dtype=object),
 array(['PTEN'], dtype=object),
 array(['BCOR', 'BAP1', 'SMARCB1'], dtype=object),
 array(['APC', 'HRAS', 'NTRK3', 'MAP2K4', 'NF1'], dtype=object),
 array(['ERBB2', 'RUNX1', 'SPEN'], dtype=object),
 array(['PIK3CA'], dtype=object),
 array(['RHOA', 'PTPRD', 'PIK3C3'], dtype=object),
 array(['ESR1', 'RPTOR', 'PIK3CB'], dtype=object),
 array(['AKT1', 'MAP3K1'], dtype=object),
 array(['ARID1B', 'SPEN'], dtype=object),
 array(['AKT1', 'PTCH1', 'LATS2', 'TP53', 'CTCF'], dtype=object),
 array(['KDM6A', 'TP53', 'NF1'], dtype=object),
 array(['PIK3CA', 'MAP2K4'], dtype=object),
 array(['PIK3CA'], dtype=object),
 array(['TP53', 'CDKN1A', 'RICTOR', 'GATA3', 'PTEN', 'RAD52', 'CREBBP',
        'BRCA1', 'PIK3CA'], dtype=object),
 array(['FLT4', 'ESR1', 'CDH1', 'JAK3', 'PPP2R1A'], dtype=object),
 array(['ESR1', 'NFE2L2', 'PIK3C2G'], dtype=object),
 array(['TP53', 'FLT4', 'DAXX', 'FBXW7'], dtype=object),
 array(['TP53', 'ARID5B', 'PALB2', 'NSD1', 'DNMT1'], dtype=object),
 array(['ARID1B', 'PIK3CA', 'PDGFRA', 'CTCF'], dtype=object),
 array(['GATA3'], dtype=object),
 array(['PTEN', 'TP53'], dtype=object),
 array(['PIK3CA', 'NSD1', 'GATA3', 'MAP3K1'], dtype=object),
 array(['PIK3CA', 'NTRK1', 'ESR1', 'AXIN1', 'PAK7'], dtype=object),
 array(['AKT1', 'TP53', 'YAP1', 'CBFB', 'CDH1'], dtype=object),
 array(['PIK3CA', 'TP53', 'EPHB1', 'CDKN2A'], dtype=object),
 array(['PIK3CA', 'MLL3', 'JAK1', 'MAP3K1', 'NOTCH4', 'PTCH1', 'NOTCH1',
        'KDM5A', 'AKT1', 'BLM', 'NF1', 'PAK7', 'BTK'], dtype=object),
 array(['RAD51B', 'GATA3'], dtype=object),
 array(['ATRX', 'MAP3K1', 'GATA3'], dtype=object),
 array(['TP53', 'SOX9'], dtype=object),
 array(['PIK3CA', 'TP53', 'BRD4'], dtype=object),
 array(['AKT1', 'SDHB', 'TMEM127', 'PIK3C2G'], dtype=object),
 array(['TP53', 'RPTOR', 'PTEN'], dtype=object),
 array(['NCOR1'], dtype=object),
 array(['TP63', 'FLT1', 'PIK3R1', 'TP53'], dtype=object),
 array(['TP53'], dtype=object),
 array(['TP53', 'FBXW7', 'RICTOR', 'BRIP1', 'BCOR', 'PIK3CA'], dtype=object),
 array(['MEN1', 'SPEN', 'ESR1', 'SOX2'], dtype=object),
 array(['SOX9', 'TP53'], dtype=object),
 array(['PIK3CA', 'MAP2K4', 'JAK3', 'ARID1A', 'TET1', 'CDH1'], dtype=object),
 array(['PIK3CA'], dtype=object),
 array(['PIK3CA', 'TP53', 'FLT3', 'NF1', 'SMARCA4'], dtype=object),
 array(['IDH1', 'ESR1', 'GATA3', 'SUZ12'], dtype=object),
 array(['TET1', 'ERCC4', 'PRKAR1A'], dtype=object),
 array(['RAD50', 'NSD1', 'NOTCH3', 'FAM175A'], dtype=object),
 array(['PIK3CA', 'CDH1'], dtype=object),
 array(['BRCA2', 'MLL3', 'MTOR', 'SPEN', 'XPO1', 'FAT1', 'PIK3R1', 'CDH1',
        'NOTCH3', 'AR'], dtype=object),
 array(['TP53', 'CCND1'], dtype=object),
 array(['TP53', 'ERCC4', 'FAT1', 'ARID2'], dtype=object),
 array(['PIK3CA', 'BARD1', 'GATA3', 'RPS6KA4', 'ERBB3', 'TBX3', 'TP53',
        'RARA'], dtype=object),
 array(['PIK3CA', 'TP53', 'ERBB2'], dtype=object),
 array(['MRE11A', 'NCOR1', 'ATRX'], dtype=object),
 array(['PIK3CA', 'INPP4A', 'CDH1'], dtype=object),
 array(['PIK3CA', 'NOTCH2', 'RFWD2', 'ERBB4', 'ATR', 'PLK2', 'MLL3',
        'RPS6KA4', 'KDM5A', 'TBX3', 'DIS3', 'NF1', 'KEAP1', 'PTPRT',
        'CDH1'], dtype=object),
 array(['TP53', 'NF1', 'CDKN2A'], dtype=object),
 array(['TERT', 'CDKN1A'], dtype=object),
 array(['PIK3CA', 'ALOX12B', 'ASXL2'], dtype=object),
 array(['TP53', 'PIK3R2', 'CDH1'], dtype=object),
 array(['TP63', 'MLL3', 'MLL', 'MLL2', 'MDM2', 'TSC2', 'MED12', 'TP53'],
       dtype=object),
 array(['TP53', 'EPCAM', 'MAP3K1', 'PTEN', 'ARID2', 'GREM1'], dtype=object),
 array(['TP53', 'PIK3CA', 'ARID1A', 'ARID2', 'MLL2', 'ERBB3', 'FLT3',
        'ERCC5', 'NF1', 'RASA1', 'MAP2K4'], dtype=object),
 array(['PIK3CA', 'MAP3K1', 'PTPRD'], dtype=object),
 array(['PIK3CA', 'TP53', 'NF1', 'TGFBR2', 'STAT3'], dtype=object),
 array(['ARID1A', 'ALK', 'GATA3'], dtype=object),
 array(['NSD1'], dtype=object),
 array(['PIK3CA', 'GATA3'], dtype=object),
 array(['TP53', 'JAK1', 'PBRM1', 'CSF1R', 'CDK8', 'BAP1'], dtype=object),
 array(['CDH1', 'FBXW7', 'TP53', 'MTOR', 'AKT3', 'PBRM1', 'RYBP', 'LATS1',
        'IKZF1', 'EZH2', 'SOX17', 'RB1', 'AXIN1', 'ERBB2'], dtype=object),
 array(['LATS2', 'ARID5B', 'RBM10'], dtype=object),
 array(['PIK3CA', 'MLL', 'GRIN2A', 'CTNNB1'], dtype=object),
 array(['PIK3CA', 'MAP3K1', 'RAD51C'], dtype=object),
 array(['GATA3', 'ATM', 'TBX3'], dtype=object),
 array(['PIK3CA', 'CD274', 'ABL1', 'DNMT3B', 'TBX3'], dtype=object),
 array(['PIK3CA', 'CDH1'], dtype=object),
 array(['ESR1', 'PDGFRA'], dtype=object),
 array(['GATA3', 'ARID1A', 'ATM', 'TCF7L2', 'TSC2', 'IDH2'], dtype=object),
 array(['PIK3CA', 'SMAD4', 'ROS1', 'ARID1A', 'RFWD2', 'CDC73', 'ATR',
        'NSD1', 'LATS1', 'IKZF1', 'MLL3', 'MYC', 'RECQL4', 'TGFBR1',
        'FGF4', 'MLL2', 'TSC2', 'ERCC4', 'NCOR1', 'SMAD2', 'EP300', 'BCOR',
        'KDM5C'], dtype=object),
 array(['TP53', 'PTPRS', 'GATA3'], dtype=object),
 array(['PIK3CA', 'GATA3', 'FGFR4', 'ROS1', 'FANCA', 'STK11', 'NF2',
        'STAG2'], dtype=object),
 array(['PIK3CA', 'EPHA5', 'H3F3C', 'TBX3', 'CBFB', 'CDH1', 'RUNX1'],
       dtype=object),
 array(['ESR1', 'RPS6KB2'], dtype=object),
 array(['GATA3', 'CIC'], dtype=object),
 array(['SPEN', 'ESR1', 'CBFB', 'GATA3'], dtype=object),
 array(['AKT1', 'PIK3CA', 'TP53', 'RUNX1', 'CTCF'], dtype=object),
 array(['TP53'], dtype=object),
 array(['GATA3'], dtype=object),
 array(['PIK3CG', 'PTCH1'], dtype=object),
 array(['PIK3CA', 'MDM2'], dtype=object),
 array(['ESR1'], dtype=object),
 array(['PIK3CA', 'IDH1', 'FLT4', 'E2F3', 'IFNGR1', 'RECQL4', 'ATM',
        'CDK8', 'IRS2', 'TP53'], dtype=object),
 array(['SPEN', 'EGFL7'], dtype=object),
 array(['ERBB3', 'ERBB2'], dtype=object),
 array(['PIK3CA', 'TP53'], dtype=object),
 array(['TP53', 'IGF1R', 'BCOR'], dtype=object),
 array(['PIK3CA', 'AURKB', 'GATA3'], dtype=object),
 array(['CREBBP'], dtype=object),
 array(['REL', 'ERCC3', 'IGF1R', 'TRAF7', 'ATRX', 'TP53'], dtype=object),
 array(['PIK3CA', 'PPP2R1A', 'MAP3K1', 'MLL3', 'CBFB', 'TBX3'],
       dtype=object),
 array(['PIK3CA', 'MAP3K1'], dtype=object),
 array(['TP53', 'PIK3CA', 'TERT', 'SMAD4'], dtype=object),
 array(['PIK3CA', 'MLL3', 'CDH1', 'NOTCH4'], dtype=object),
 array(['ESR1', 'MLL3', 'CDH1'], dtype=object),
 array(['TP53', 'ARID1B', 'STAG2'], dtype=object),
 array(['TP53', 'EPHB1', 'NF1', 'ASXL1', 'SRC', 'PIK3R1'], dtype=object),
 array(['IKBKE', 'TP53'], dtype=object),
 array(['GRIN2A', 'GATA3'], dtype=object),
 array(['AKT1'], dtype=object),
 array(['TP53', 'PIK3CA', 'ATM', 'FAT1', 'PNRC1', 'NF1'], dtype=object),
 array(['TP53', 'CSF1R', 'PTPRD', 'SPEN', 'HNF1A'], dtype=object),
 array(['ESR1', 'RICTOR'], dtype=object),
 array(['SF3B1', 'PTEN', 'ERBB2', 'CDH1'], dtype=object),
 array(['HNF1A', 'TP53', 'CDH1'], dtype=object),
 array(['ESR1', 'CREBBP'], dtype=object),
 array(['TP53', 'RPTOR', 'RUNX1'], dtype=object),
 array(['FBXW7', 'FLT4', 'RBM10', 'TP53'], dtype=object),
 array(['PIK3CA', 'RASA1', 'JAK3', 'TP53'], dtype=object),
 array(['GATA3', 'TP53'], dtype=object),
 array(['PIK3CA', 'TP53', 'FGFR4', 'LATS2'], dtype=object),
 array(['TP53', 'ASXL1', 'SMARCB1'], dtype=object),
 array(['AKT1', 'SF3B1', 'ERBB4', 'RAD50'], dtype=object),
 array(['PIK3CA', 'SPEN', 'ESR1', 'GATA3'], dtype=object),
 array(['PIK3CA', 'FAT1', 'RB1'], dtype=object),
 array(['SMAD4', 'ERBB3', 'RFWD2', 'PBRM1', 'CARD11', 'TP53'], dtype=object),
 array(['GATA3', 'RBM10'], dtype=object),
 array(['PIK3CA', 'GATA3', 'FOXA1', 'CBFB', 'ERBB2', 'MAP3K1'],
       dtype=object),
 array(['PIK3CA', 'CTCF', 'NKX3-1', 'MAP2K4', 'FOXP1', 'GATA3'],
       dtype=object),
 array(['MLL', 'TP53', 'NF1'], dtype=object),
 array(['PIK3CA', 'EPHA5', 'RECQL4', 'NOTCH1', 'TP53'], dtype=object),
 array(['TP53'], dtype=object),
 array(['AR', 'DDR2', 'TP53', 'NF1', 'PTEN'], dtype=object),
 array(['SF3B1', 'TP53', 'GATA3'], dtype=object),
 array(['KRAS', 'PIK3CA', 'CDK8', 'SPEN', 'ARID1A', 'RAD54L', 'ALK',
        'SOX2', 'FGFR3', 'PLK2', 'APC', 'MDC1', 'NOTCH4', 'MLL3', 'ARID5B',
        'MEN1', 'FOXA1', 'CREBBP', 'NCOR1', 'MAP2K2', 'NOTCH3', 'DNMT3B',
        'CDH1', 'XPO1'], dtype=object),
 array(['TP53'], dtype=object),
 array(['RARA', 'NOTCH3'], dtype=object),
 array(['TP53', 'SOX2', 'ROS1', 'LATS1', 'TSC2'], dtype=object),
 array(['PTEN', 'JAK3'], dtype=object),
 array(['PARP1', 'XPO1', 'MAP2K4', 'KEAP1', 'APC'], dtype=object),
 array(['ESR1', 'MLL2', 'CIC', 'ARID1A', 'MAP2K4'], dtype=object),
 array(['PIK3CA', 'TET2', 'GNA11', 'AKT2', 'PTPRT'], dtype=object),
 array(['TP53', 'NOTCH3'], dtype=object),
 array(['AKT1', 'PIK3CA', 'TERT', 'ESR1', 'CTCF', 'MAP3K1', 'BCOR'],
       dtype=object),
 array(['TET2', 'TBX3', 'ALOX12B', 'CDH1'], dtype=object),
 array(['PIK3CA', 'DOT1L', 'STAG2', 'CDH1'], dtype=object),
 array(['MLL3', 'NF1', 'ASXL1', 'PIK3R1', 'PTEN'], dtype=object),
 array(['ESR1'], dtype=object),
 array(['PIK3CA', 'ESR1', 'BRIP1', 'KDM5C'], dtype=object),
 array(['SPEN', 'PIK3R1', 'FGF3', 'RB1', 'TP53'], dtype=object),
 array(['NSD1', 'GATA3'], dtype=object),
 array(['TP53'], dtype=object),
 array(['PIK3CA', 'IRS1', 'TP53', 'SOX9'], dtype=object),
 array(['TP53', 'SMO', 'BLM', 'EGFL7'], dtype=object),
 array(['PIK3CA', 'MDC1', 'BCOR'], dtype=object),
 array(['ERBB2', 'BCL6', 'MET', 'TBX3', 'STAT3'], dtype=object),
 array(['AR'], dtype=object),
 array(['MLL3', 'TP53'], dtype=object),
 array(['DNMT3A', 'AXL'], dtype=object),
 array(['AXIN2', 'ARID1A', 'PIK3CA', 'TP53', 'PTEN'], dtype=object),
 array(['PIK3CA', 'CDH1', 'ARID1A', 'PIK3R3', 'JAK1', 'RIT1', 'SDHC',
        'ERCC3', 'CUL3', 'SETD2', 'MAP3K13', 'KIT', 'APC', 'RAD50',
        'CDKN1A', 'IKZF1', 'EGFR', 'JAK2', 'CD274', 'ABL1', 'PAK1',
        'PIK3C2G', 'ARID2', 'LATS2', 'FLT3', 'BLM', 'CREBBP', 'ERCC4',
        'SUZ12', 'STK11', 'JAK3', 'ASXL1', 'TOP1', 'SMARCB1', 'MED12'],
       dtype=object),
 array(['AKT1', 'KDM6A', 'FLT4', 'MAP2K4', 'NCOR1'], dtype=object),
 array(['MAP3K1'], dtype=object),
 array(['PIK3CA', 'ARID1A', 'CDH1'], dtype=object),
 array(['AKT3', 'MAP3K1', 'NSD1', 'MLL3', 'MDM2', 'SMAD4'], dtype=object),
 array(['DNMT3A', 'RHOA', 'CDH1', 'KDM6A'], dtype=object),
 array(['FAT1', 'TP53', 'RASA1', 'CDH1'], dtype=object),
 array(['SF3B1', 'TERT', 'FOXA1'], dtype=object),
 array(['NFE2L2', 'MLL2', 'RAD51', 'PRKAR1A', 'ROS1'], dtype=object),
 array(['ATR', 'FGF3', 'DNMT3B', 'TP53'], dtype=object),
 array(['SETD2', 'ESR1', 'LATS2'], dtype=object),
 array(['PIK3CA', 'TBX3'], dtype=object),
 array(['ESR1', 'PIK3CA', 'IKZF1', 'NCOR1', 'CDH1', 'MAP3K1'], dtype=object),
 array(['VHL', 'EZH2', 'PIK3CA', 'SETD2', 'TP53'], dtype=object),
 array(['TP53', 'ARID1A', 'ALK', 'WT1', 'RBM10', 'BRCA1'], dtype=object),
 array(['PIK3CA', 'RYBP', 'FAM175A', 'MAP3K1', 'SMO', 'MEN1', 'TP53',
        'MLL3', 'CDK8'], dtype=object),
 array(['KDM6A', 'ATRX', 'TP53', 'JAK3'], dtype=object),
 array(['MEN1', 'TRAF7', 'NOTCH3', 'GATA3'], dtype=object),
 array(['KDM6A', 'ERCC4', 'GATA3'], dtype=object),

In [ ]:
## Process Patient id column for data mutation
#df_data_protein['protein1'] = df_data_protein['protein1'].map(lambda x: x.lstrip('9606.').rstrip('aAbBcC'))
#df_data_mut['Tumor_Sample_Barcode'] = df_data_mut['Tumor_Sample_Barcode'].str.replace(r'\"d','')
#df_data_mut['protein1Tumor_Sample_Barcode_new'] = df_data_mut['Tumor_Sample_Barcode'].map(lambda x: x.rstrip('P-00%-').rstrip())

In [ ]:
df_data_mut

,Unnamed: 0,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,...,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,cDNA_change,protein1Tumor_Sample_Barcode_new,protein1Tumor_Sample_Barcode_new_1
0,0,SPEN,NaN,NaN,GRCh37,1,16265908,16265908,+,missense_variant,...,p.Ile3661Phe,p.I3661F,ENST00000375759,NM_015001.2,3661.0,Att/Ttt,0,c.10981A>T,P-0000004,P-0000004
1,1,ALK,NaN,NaN,GRCh37,2,29543736,29543736,+,missense_variant,...,p.Val476Ala,p.V476A,ENST00000389048,NM_004304.4,476.0,gTg/gCg,0,c.1427T>C,P-0000004,P-0000004
2,2,PDCD1,NaN,NaN,GRCh37,2,242793433,242793433,+,missense_variant,...,p.Ala215Val,p.A215V,ENST00000334409,NM_005018.2,215.0,gCc/gTc,0,c.644C>T,P-0000004,P-0000004
3,3,MAP3K1,NaN,NaN,GRCh37,5,56177843,56177843,+,missense_variant,...,p.Ser939Cys,p.S939C,ENST00000399503,NM_005921.1,939.0,tCt/tGt,0,c.2816C>G,P-0000004,P-0000004
4,4,FLT4,NaN,NaN,GRCh37,5,180030313,180030313,+,missense_variant,...,p.Arg1324Leu,p.R1324L,ENST00000261937,NM_182925.4,1324.0,cGg/cTg,0,c.3971G>T,P-0000004,P-0000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78258,78258,BCL2,NaN,NaN,GRCh37,18,60985808,60985808,+,missense_variant,...,p.Asp31Gly,p.D31G,ENST00000333681,NaN,31.0,gAt/gGt,0,c.92A>G,P-0012524-T01-IM5,P-0012524-T01-IM5
78259,78259,TNFRSF14,NaN,NaN,GRCh37,1,2489268,2489269,+,frameshift_variant,...,p.Gly60SerfsTer18,p.G60Sfs*18,ENST00000355716,NM_003820.2,58.0,agt/agTCCAt,0,c.174_177dupTCCA,P-0012524-T01-IM5,P-0012524-T01-IM5
78260,78260,TNFAIP3,NaN,NaN,GRCh37,6,138196871,138196872,+,frameshift_variant,...,p.Pro180HisfsTer73,p.P180Hfs*73,ENST00000237289,NM_001270507.1,178.0,gAC/g,0,c.537_538delAC,P-0012524-T01-IM5,P-0012524-T01-IM5
78261,78261,MLL2,NaN,NaN,GRCh37,12,49440414,49440415,+,frameshift_variant,...,p.Lys1466GlnfsTer25,p.K1466Qfs*25,ENST00000301067,NM_003482.3,1465.0,-/C,0,c.4395dupC,P-0012524-T01-IM5,P-0012524-T01-IM5
78262,78262,CDKN2A,NaN,NaN,GRCh37,9,21971170,21971170,+,missense_variant,...,p.Leu63Gln,p.L63Q,ENST00000304494,NM_000077.4,63.0,cTg/cAg,0,c.188T>A,P-0005919-T01-IM5,P-0005919-T01-IM5

In [ ]:
print(df_data_mut.columns)

Index(['Unnamed: 0', 'Hugo_Symbol', 'Entrez_Gene_Id', 'Center', 'NCBI_Build',
       'Chromosome', 'Start_Position', 'End_Position', 'Strand', 'Consequence',
       'Variant_Classification', 'Variant_Type', 'Reference_Allele',
       'Tumor_Seq_Allele1', 'Tumor_Seq_Allele2', 'dbSNP_RS',
       'dbSNP_Val_Status', 'Tumor_Sample_Barcode',
       'Matched_Norm_Sample_Barcode', 'Match_Norm_Seq_Allele1',
       'Match_Norm_Seq_Allele2', 'Tumor_Validation_Allele1',
       'Tumor_Validation_Allele2', 'Match_Norm_Validation_Allele1',
       'Match_Norm_Validation_Allele2', 'Verification_Status',
       'Validation_Status', 'Mutation_Status', 'Sequencing_Phase',
       'Sequence_Source', 'Validation_Method', 'Score', 'BAM_File',
       'Sequencer', 't_ref_count', 't_alt_count', 'n_ref_count', 'n_alt_count',
       'HGVSc', 'HGVSp', 'HGVSp_Short', 'Transcript_ID', 'RefSeq',
       'Protein_position', 'Codons', 'Hotspot', 'cDNA_change',
       'protein1Tumor_Sample_Barcode_new',
       'protein1Tumor_Sample_Barcode_new_1'],
      dtype='object')

In [ ]:
df_data_mut_final=df_data_mut[['Hugo_Symbol','NCBI_Build','Chromosome','Start_Position','End_Position','Strand','Consequence','Variant_Type','Reference_Allele','Tumor_Seq_Allele2','Tumor_Sample_Barcode','Transcript_ID','RefSeq']]

In [ ]:
#df_data_mut_final.head(5)
df_data_mut_final

,Hugo_Symbol,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Type,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Transcript_ID,RefSeq
0,SPEN,GRCh37,1,16265908,16265908,+,missense_variant,SNP,A,T,P-0000004,ENST00000375759,NM_015001.2
1,ALK,GRCh37,2,29543736,29543736,+,missense_variant,SNP,A,G,P-0000004,ENST00000389048,NM_004304.4
2,PDCD1,GRCh37,2,242793433,242793433,+,missense_variant,SNP,G,A,P-0000004,ENST00000334409,NM_005018.2
3,MAP3K1,GRCh37,5,56177843,56177843,+,missense_variant,SNP,C,G,P-0000004,ENST00000399503,NM_005921.1
4,FLT4,GRCh37,5,180030313,180030313,+,missense_variant,SNP,C,A,P-0000004,ENST00000261937,NM_182925.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78258,BCL2,GRCh37,18,60985808,60985808,+,missense_variant,SNP,T,C,P-0012524,ENST00000333681,NaN
78259,TNFRSF14,GRCh37,1,2489268,2489269,+,frameshift_variant,INS,-,TCCA,P-0012524,ENST00000355716,NM_003820.2
78260,TNFAIP3,GRCh37,6,138196871,138196872,+,frameshift_variant,DEL,AC,-,P-0012524,ENST00000237289,NM_001270507.1
78261,MLL2,GRCh37,12,49440414,49440415,+,frameshift_variant,INS,-,G,P-0012524,ENST00000301067,NM_003482.3
78262,CDKN2A,GRCh37,9,21971170,21971170,+,missense_variant,SNP,A,T,P-0005919,ENST00000304494,NM_000077.4

In [ ]:
df_data_mut_final['Tumor_Sample_Barcode'].value_counts()

P-0012358    456
P-0004379    444
P-0007319    423
P-0003900    419
P-0004688    416
            ...
P-0008436      1
P-0008441      1
P-0008430      1
P-0000733      1
P-0006520      1
Name: Tumor_Sample_Barcode, Length: 9594, dtype: int64

In [ ]:
df_data_mut_final['Tumor_Sample_Barcode'].nunique()

9594

In [ ]:
df_data_mut_final['Variant_Type'].value_counts()

SNP    65970
DEL     8201
INS     2910
DNP     1039
TNP       81
ONP       62
Name: Variant_Type, dtype: int64

In [ ]:
df_data_mut_final['Chromosome'].value_counts()

17    9220
3     6406
12    5916
5     5803
1     5149
19    4776
7     4253
2     3875
16    3749
6     3744
X     3678
4     3313
9     3304
11    2818
13    2428
10    2249
20    1832
15    1563
14    1043
18     992
22     852
8      799
21     501
Name: Chromosome, dtype: int64

In [ ]:
df_data_mut_final['Consequence'].value_counts()

missense_variant                                                                                  53887
frameshift_variant                                                                                 8595
stop_gained                                                                                        7536
missense_variant,splice_region_variant                                                             1669
upstream_gene_variant                                                                              1359
inframe_deletion                                                                                   1224
splice_acceptor_variant                                                                            1188
splice_donor_variant                                                                               1050
stop_gained,splice_region_variant                                                                   272
inframe_insertion                                                                                   269
frameshift_variant,splice_region_variant                                                            178
splice_donor_variant,coding_sequence_variant,intron_variant                                         173
splice_acceptor_variant,coding_sequence_variant,intron_variant                                      163
protein_altering_variant                                                                            112
start_lost                                                                                          104
stop_gained,frameshift_variant                                                                       97
splice_donor_variant,coding_sequence_variant                                                         60
splice_acceptor_variant,coding_sequence_variant                                                      50
stop_lost                                                                                            43
downstream_gene_variant                                                                              35
intron_variant                                                                                       29
inframe_deletion,splice_region_variant                                                               24
splice_acceptor_variant,intron_variant                                                               23
splice_acceptor_variant,splice_donor_variant,coding_sequence_variant,intron_variant                  14
5_prime_UTR_variant                                                                                  14
splice_donor_variant,intron_variant                                                                  12
stop_gained,inframe_deletion                                                                         11
coding_sequence_variant,3_prime_UTR_variant                                                          10
stop_gained,frameshift_variant,splice_region_variant                                                  7
splice_region_variant,intron_variant                                                                  7
protein_altering_variant,splice_region_variant                                                        6
stop_gained,inframe_insertion                                                                         6
inframe_insertion,splice_region_variant                                                               5
coding_sequence_variant,5_prime_UTR_variant                                                           3
splice_donor_variant,non_coding_transcript_variant                                                    3
stop_gained,protein_altering_variant                                                                  3
frameshift_variant,start_lost                                                                         2
splice_acceptor_variant,splice_donor_variant,intron_variant                                           2
start_lost,splice_region_variant                                                                      2
stop_gained,inframe_insertion,splice_region_variant                                                   2
frameshift_variant,stop_lost                                                                          2
frameshift_variant,start_lost,start_retained_variant                                                  2
stop_gained,protein_altering_variant,splice_region_variant                                            1
splice_donor_variant,coding_sequence_variant,5_prime_UTR_variant,intron_variant                       1
splice_acceptor_variant,frameshift_variant,intron_variant                                             1
splice_acceptor_variant,splice_donor_variant,frameshift_variant,stop_lost,intron_variant              1
splice_donor_variant,coding_sequence_variant,3_prime_UTR_variant,intron_variant                       1
splice_acceptor_variant,splice_donor_variant,stop_lost,inframe_deletion,intron_variant                1
splice_acceptor_variant,splice_donor_variant,stop_lost,protein_altering_variant,intron_variant        1
splice_acceptor_variant,intron_variant,non_coding_transcript_variant                                  1
splice_acceptor_variant,non_coding_transcript_variant                                                 1
stop_gained,inframe_deletion,splice_region_variant                                                    1
Name: Consequence, dtype: int64

In [ ]:

df_data_mut_snp=df_data_mut_final[df_data_mut_final['Variant_Type']=='SNP']

In [ ]:
df_data_mut_test=df_data_mut_final[df_data_mut_final['Start_Position']==39817481]
df_data_mut_test

,Hugo_Symbol,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Type,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Transcript_ID,RefSeq
402,ERG,GRCh37,21,39817481,39817481,+,missense_variant,SNP,G,T,P-0000157,ENST00000288319,NM_182918.3

In [ ]:
print(df_data_mut_final[df_data_mut_final['Start_Position']==44514647])

      Hugo_Symbol NCBI_Build Chromosome  Start_Position  End_Position Strand  \
25          U2AF1     GRCh37         21        44514647      44514647      +
20228       U2AF1     GRCh37         21        44514647      44514647      +

            Consequence Variant_Type Reference_Allele Tumor_Seq_Allele2  \
25     missense_variant          SNP                T                 C
20228  missense_variant          SNP                T                 C

      Tumor_Sample_Barcode    Transcript_ID       RefSeq
25       P-0000023-T01-IM3  ENST00000291552  NM_006758.2
20228    P-0003690-T01-IM5  ENST00000291552  NM_006758.2

In [ ]:
df_data_mut_snp.head(5)

,Hugo_Symbol,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Type,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Transcript_ID,RefSeq
0,SPEN,GRCh37,1,16265908,16265908,+,missense_variant,SNP,A,T,P-0000004-T01-IM3,ENST00000375759,NM_015001.2
1,ALK,GRCh37,2,29543736,29543736,+,missense_variant,SNP,A,G,P-0000004-T01-IM3,ENST00000389048,NM_004304.4
2,PDCD1,GRCh37,2,242793433,242793433,+,missense_variant,SNP,G,A,P-0000004-T01-IM3,ENST00000334409,NM_005018.2
3,MAP3K1,GRCh37,5,56177843,56177843,+,missense_variant,SNP,C,G,P-0000004-T01-IM3,ENST00000399503,NM_005921.1
4,FLT4,GRCh37,5,180030313,180030313,+,missense_variant,SNP,C,A,P-0000004-T01-IM3,ENST00000261937,NM_182925.4

In [ ]:
df_data_mut_snp_chr_pat=df_data_mut_final.groupby(['Chromosome','Tumor_Sample_Barcode']).first()

In [ ]:
df_data_mut_snp_chr_pat

                                Hugo_Symbol NCBI_Build  Start_Position  \
Chromosome Tumor_Sample_Barcode
1          P-0000004-T01-IM3           SPEN     GRCh37        16265908
           P-0000024-T01-IM3         ARID1A     GRCh37        27105878
           P-0000034-T01-IM3         ARID1A     GRCh37        27023307
           P-0000037-T01-IM3          MYCL1     GRCh37        40363378
           P-0000043-T02-IM3         NOTCH2     GRCh37       120458129
...                                     ...        ...             ...
X          P-0012397-T01-IM5           BCOR     GRCh37        39933151
           P-0012400-T01-IM5          KDM5C     GRCh37        53245051
           P-0012402-T01-IM5          CRLF2     GRCh37         1327732
           P-0012557-T01-IM5          KDM6A     GRCh37        44922802
           P-0012622-T01-IM5           ATRX     GRCh37        76855914

                                 End_Position Strand         Consequence  \
Chromosome Tumor_Sample_Barcode
1          P-0000004-T01-IM3         16265908      +    missense_variant
           P-0000024-T01-IM3         27105881      +  frameshift_variant
           P-0000034-T01-IM3         27023307      +         stop_gained
           P-0000037-T01-IM3         40363378      +    missense_variant
           P-0000043-T02-IM3        120458129      +    missense_variant
...                                       ...    ...                 ...
X          P-0012397-T01-IM5         39933151      +    missense_variant
           P-0012400-T01-IM5         53245051      +         stop_gained
           P-0012402-T01-IM5          1327732      +    missense_variant
           P-0012557-T01-IM5         44922802      +         stop_gained
           P-0012622-T01-IM5         76855914      +         stop_gained

                                Variant_Type Reference_Allele  \
Chromosome Tumor_Sample_Barcode
1          P-0000004-T01-IM3             SNP                A
           P-0000024-T01-IM3             DEL             AGCT
           P-0000034-T01-IM3             SNP                C
           P-0000037-T01-IM3             SNP                A
           P-0000043-T02-IM3             SNP                C
...                                      ...              ...
X          P-0012397-T01-IM5             SNP                G
           P-0012400-T01-IM5             SNP                C
           P-0012402-T01-IM5             SNP                T
           P-0012557-T01-IM5             SNP                C
           P-0012622-T01-IM5             SNP                T

                                Tumor_Seq_Allele2    Transcript_ID  \
Chromosome Tumor_Sample_Barcode
1          P-0000004-T01-IM3                    T  ENST00000375759
           P-0000024-T01-IM3                    -  ENST00000324856
           P-0000034-T01-IM3                    G  ENST00000324856
           P-0000037-T01-IM3                    C  ENST00000397332
           P-0000043-T02-IM3                    A  ENST00000256646
...                                           ...              ...
X          P-0012397-T01-IM5                    A  ENST00000378444
           P-0012400-T01-IM5                    A  ENST00000375401
           P-0012402-T01-IM5                    G  ENST00000381566
           P-0012557-T01-IM5                    T  ENST00000377967
           P-0012622-T01-IM5                    A  ENST00000373344

                                         RefSeq
Chromosome Tumor_Sample_Barcode
1          P-0000004-T01-IM3        NM_015001.2
           P-0000024-T01-IM3        NM_006015.4
           P-0000034-T01-IM3        NM_006015.4
           P-0000037-T01-IM3     NM_001033082.2
           P-0000043-T02-IM3        NM_024408.3
...                                         ...
X          P-0012397-T01-IM5     NM_001123385.1
           P-0012400-T01-IM5        NM_004187.3
           P-0012402-T01-IM5        NM_005089.3
           P-0012557-T01-IM5        NM_021140.2
           P-0012622-T01-IM5        NM_000489.3

[48005 rows x 11 columns]

In [ ]:

df_data_mut_snp_chr5=df_data_mut[df_data_mut['Chromosome']=='21']

In [ ]:
df_data_mut_snp_chr5.head(5)

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,n_alt_count,HGVSc,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,cDNA_change
25,U2AF1,NaN,NaN,GRCh37,21,44514647,44514647,+,missense_variant,Missense_Mutation,...,NaN,ENST00000291552.4:c.509A>G,p.Asn170Ser,p.N170S,ENST00000291552,NM_006758.2,170.0,aAc/aGc,0,c.509A>G
133,U2AF1,NaN,NaN,GRCh37,21,44527561,44527561,+,"missense_variant,splice_region_variant",Missense_Mutation,...,NaN,ENST00000291552.4:c.44A>G,p.Lys15Arg,p.K15R,ENST00000291552,NM_006758.2,15.0,aAa/aGa,0,c.44A>G
267,TMPRSS2,NaN,NaN,GRCh37,21,42866328,42866328,+,missense_variant,Missense_Mutation,...,NaN,ENST00000398585.3:c.304G>A,p.Val102Ile,p.V102I,ENST00000398585,NM_001135099.1,102.0,Gtc/Atc,0,c.304G>A
402,ERG,NaN,NaN,GRCh37,21,39817481,39817481,+,missense_variant,Missense_Mutation,...,NaN,ENST00000288319.7:c.82C>A,p.Leu28Met,p.L28M,ENST00000288319,NM_182918.3,28.0,Ctg/Atg,0,c.82C>A
566,RUNX1,NaN,NaN,GRCh37,21,36252988,36252988,+,frameshift_variant,Frame_Shift_Del,...,NaN,ENST00000300305.3:c.374delC,p.Pro125GlnfsTer8,p.P125Qfs*8,ENST00000300305,NaN,125.0,cCa/ca,0,c.374delC

In [ ]:
! wget --timestamping "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/latest/hg19.fa.gz"

--2022-07-15 15:58:03--  https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/latest/hg19.fa.gz
Resolving hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)|128.114.119.163|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 979164575 (934M) [application/x-gzip]
Saving to: ‘hg19.fa.gz’

hg19.fa.gz          100%[===================>] 933.80M  37.5MB/s    in 26s

2022-07-15 15:58:30 (36.4 MB/s) - ‘hg19.fa.gz’ saved [979164575/979164575]

In [ ]:
! pip install Bio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Bio
  Downloading bio-1.3.9-py3-none-any.whl (270 kB)
     |████████████████████████████████| 270 kB 30.8 MB/s
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from Bio) (4.64.0)
Collecting biopython>=1.79
  Downloading biopython-1.79-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 44.6 MB/s
Collecting mygene
  Downloading mygene-3.2.2-py2.py3-none-any.whl (5.4 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from Bio) (2.23.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from biopython>=1.79->Bio) (1.21.6)
Collecting biothings-client>=0.2.6
  Downloading biothings_client-0.2.6-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->Bio) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->Bio) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->Bio) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->Bio) (2022.6.15)
Installing collected packages: biothings-client, mygene, biopython, Bio
Successfully installed Bio-1.3.9 biopython-1.79 biothings-client-0.2.6 mygene-3.2.2

In [ ]:
from Bio import SeqIO


fasta_sequences = SeqIO.parse(open("/content/hg19.fa.gz"),'fasta')

In [ ]:
import gzip
from Bio import SeqIO

with gzip.open("hg19.fa.gz", "rt") as handle:
 
    for record in SeqIO.parse(handle, "fasta"):
        #print(record)
        if (record.id=="chr9"):
          with open('chrx.txt','w')as f:
            f.write(f'{record.seq}')

          #print(str(record.seq))

In [ ]:
#with gzip.open("hg19.fa.gz", "rt") as handle:
#file = gzip.open("hg19.fa.gz", "rt")
file = open("chrx.txt", "r")
list_chr21=[]
while 1:
     
    # read by character
    char = file.read(1)    
    list_chr21.append(char)   
    if not char:
        break
         
    #print(char)
 
file.close()

In [ ]:
## before subsitution
list_chr21[39817481]

'C'

In [ ]:
df_data_mut_snp_chr5 = df_data_mut_snp_chr5.fillna(0)

In [ ]:
## checking initial nucleotide
list_chr21[44514647]

'T'

In [ ]:
list_start=df_data_mut_snp_chr5['Start_Position'].to_list()
list_tumor_seq=df_data_mut_snp_chr5['Tumor_Seq_Allele2'].to_list()

In [ ]:
for x in range(len(list_start)):
  list_chr21[list_start[x]]=list_tumor_seq[x]

In [ ]:
# after subsitution
list_chr21[39817481]

'T'

In [ ]:
list_chr21[44514647]

'C'

In [ ]:
## Create K-Mers for this

In [ ]:
df_data_mut_dnp=df_data_mut_final[df_data_mut_final['Variant_Type']=='DNP']

In [ ]:
df_data_mut_dnp

,Hugo_Symbol,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Type,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Transcript_ID,RefSeq
177,TP53,GRCh37,17,7577516,7577517,+,missense_variant,DNP,GA,AG,P-0000105-T01-IM3,ENST00000269305,NM_001126112.2
513,CREBBP,GRCh37,16,3801734,3801735,+,missense_variant,DNP,GC,AA,P-0000088-T01-IM3,ENST00000262367,NM_004380.2
720,ASXL1,GRCh37,20,31023625,31023626,+,stop_gained,DNP,GG,AA,P-0000237-T01-IM3,ENST00000375687,NM_015338.5
928,ERCC2,GRCh37,19,45858091,45858092,+,missense_variant,DNP,CC,AT,P-0000083-T01-IM3,ENST00000391945,NM_000400.3
930,PAX5,GRCh37,9,37020683,37020684,+,missense_variant,DNP,GA,TT,P-0000083-T01-IM3,ENST00000358127,NM_001280556.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77919,MCL1,GRCh37,1,150551555,150551556,+,missense_variant,DNP,CC,TG,P-0009925-T01-IM5,ENST00000369026,NM_021960.4
77947,KRAS,GRCh37,12,25398285,25398286,+,missense_variant,DNP,CA,AG,P-0010173-T01-IM5,ENST00000256078,NM_033360.2
77956,PAK7,GRCh37,20,9561465,9561466,+,missense_variant,DNP,GG,TT,P-0010173-T01-IM5,ENST00000353224,NM_177990.2
78109,CCND1,GRCh37,11,69456219,69456220,+,missense_variant,DNP,AT,TG,P-0011204-T01-IM5,ENST00000227507,NM_053056.2
78180,BCL2,GRCh37,18,60985876,60985877,+,missense_variant,DNP,CC,TT,P-0011582-T01-IM5,ENST00000333681,NaN

In [ ]:
df_data_mut_dnp_chr21=df_data_mut_dnp[df_data_mut_dnp['Chromosome']=='21']

In [ ]:
df_data_mut_dnp_chr21.head(10)

,Hugo_Symbol,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Type,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Transcript_ID,RefSeq
6600,RUNX1,GRCh37,21,36171735,36171736,+,missense_variant,DNP,GG,AA,P-0001229-T01-IM3,ENST00000300305,NaN
12264,TMPRSS2,GRCh37,21,42842637,42842638,+,missense_variant,DNP,CC,AA,P-0002316-T01-IM3,ENST00000398585,NM_001135099.1
28436,RUNX1,GRCh37,21,36164717,36164718,+,missense_variant,DNP,GG,AA,P-0004831-T01-IM5,ENST00000300305,NaN
35443,ICOSLG,GRCh37,21,45649972,45649973,+,"splice_acceptor_variant,coding_sequence_variant",DNP,CC,AA,P-0005827-T01-IM5,ENST00000407780,NM_001283052.1
38544,TMPRSS2,GRCh37,21,42866306,42866307,+,missense_variant,DNP,GG,AA,P-0006216-T01-IM5,ENST00000398585,NM_001135099.1
40585,RUNX1,GRCh37,21,36259178,36259179,+,missense_variant,DNP,GC,AA,P-0006456-T01-IM5,ENST00000300305,NaN
42872,ERG,GRCh37,21,39755530,39755531,+,missense_variant,DNP,GG,AA,P-0006754-T01-IM5,ENST00000288319,NM_182918.3
63855,ICOSLG,GRCh37,21,45657056,45657057,+,missense_variant,DNP,CC,TT,P-0010340-T01-IM5,ENST00000407780,NM_001283052.1
71310,ERG,GRCh37,21,39755518,39755519,+,missense_variant,DNP,GG,AA,P-0011432-T01-IM5,ENST00000288319,NM_182918.3
72656,ICOSLG,GRCh37,21,45649965,45649966,+,missense_variant,DNP,CC,AA,P-0012076-T01-IM5,ENST00000407780,NM_001283052.1

In [ ]:
list_start_dnp=df_data_mut_dnp_chr21['Start_Position'].to_list()
list_end_dnp=df_data_mut_dnp_chr21['End_Position'].to_list()
list_tumor_seq_dnp=df_data_mut_dnp_chr21['Tumor_Seq_Allele2'].to_list()

In [ ]:
print(list_tumor_seq_dnp[3])

AA

In [ ]:
!pip install iteration_utilities

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting iteration_utilities
  Downloading iteration_utilities-0.11.0-cp37-cp37m-manylinux2014_x86_64.whl (283 kB)
     |████████████████████████████████| 283 kB 29.5 MB/s
Installing collected packages: iteration-utilities
Successfully installed iteration-utilities-0.11.0

In [ ]:
from iteration_utilities import deepflatten
res_dnp_1=[]
for x in range(len(list_start_dnp)):
   res_dnp_1=(list(list_tumor_seq_dnp[x]))
   print(res_dnp_1)
   print(list_chr21[list_start_dnp[x]:list_end_dnp[x]+1])
   print(" after subsituting")
   list_chr21[list_start_dnp[x]:list_end_dnp[x]+1]=list(deepflatten(res_dnp_1))
   print(list_chr21[list_start_dnp[x]:list_end_dnp[x]+1])
   #print(list_chr21[list_start_dnp[x]])

['A', 'A']
['AA', 'A']
 after subsituting
['A', 'A']
['A', 'A']
['AA', 'C']
 after subsituting
['A', 'A']
['A', 'A']
['AA', 'C']
 after subsituting
['A', 'A']
['A', 'A']
['AA', 'C']
 after subsituting
['A', 'A']
['A', 'A']
['AA', 'A']
 after subsituting
['A', 'A']
['A', 'A']
['A', 't']
 after subsituting
['A', 'A']
['A', 'A']
['AA', 'a']
 after subsituting
['A', 'A']
['T', 'T']
['TT', 'a']
 after subsituting
['T', 'T']
['A', 'A']
['AA', 'T']
 after subsituting
['A', 'A']
['A', 'A']
['AA', 'T']
 after subsituting
['A', 'A']